// Code generated by sdk/gen/gen_clients.py. DO NOT EDIT.
import type { Client } from './client.js'
import type { JsonValue, RequestOptions } from './types.js'

export type PathParams = Record<string, string | number>

/** All OpenAPI operationIds as client methods. */
export class Resources {
  constructor(private readonly client: Client) {}

  async getMe(options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/me"
    return this.client.request({
      ...options,
      method: 'GET',
      path,
    })
  }

  async getMeStatistics(options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/me/statistics"
    return this.client.request({
      ...options,
      method: 'GET',
      path,
    })
  }

  async getMePositions(options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/me/positions"
    return this.client.request({
      ...options,
      method: 'GET',
      path,
    })
  }

  async getMePositionlegs(options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/me/position-legs"
    return this.client.request({
      ...options,
      method: 'GET',
      path,
    })
  }

  async getMeOrders(options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/me/orders"
    return this.client.request({
      ...options,
      method: 'GET',
      path,
    })
  }

  async getMeSignals(options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/me/signals"
    return this.client.request({
      ...options,
      method: 'GET',
      path,
    })
  }

  async getMeEmitters(options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/me/emitters"
    return this.client.request({
      ...options,
      method: 'GET',
      path,
    })
  }

  async postMeEmittersSummary(body?: JsonValue, options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/me/emitters/summary"
    return this.client.request({
      ...options,
      method: 'POST',
      path,
      body: body ?? options?.body,
    })
  }

  async postAutomationsSummary(body?: JsonValue, options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/automations/summary"
    return this.client.request({
      ...options,
      method: 'POST',
      path,
      body: body ?? options?.body,
    })
  }

  async getFollowers(options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/followers"
    return this.client.request({
      ...options,
      method: 'GET',
      path,
    })
  }

  async postFollowers(body?: JsonValue, options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/followers"
    return this.client.request({
      ...options,
      method: 'POST',
      path,
      body: body ?? options?.body,
      write: true,
    })
  }

  async getFollowersById(pathParams: PathParams, options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/followers/" + encodeURIComponent(String(pathParams.id)) + ""
    return this.client.request({
      ...options,
      method: 'GET',
      path,
    })
  }

  async patchFollowersById(pathParams: PathParams, body?: JsonValue, options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/followers/" + encodeURIComponent(String(pathParams.id)) + ""
    return this.client.request({
      ...options,
      method: 'PATCH',
      path,
      body: body ?? options?.body,
      write: true,
    })
  }

  async deleteFollowersById(pathParams: PathParams, body?: JsonValue, options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/followers/" + encodeURIComponent(String(pathParams.id)) + ""
    return this.client.request({
      ...options,
      method: 'DELETE',
      path,
      body: body ?? options?.body,
      write: true,
    })
  }

  async postFollowersSummary(body?: JsonValue, options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/followers/summary"
    return this.client.request({
      ...options,
      method: 'POST',
      path,
      body: body ?? options?.body,
    })
  }

  async getFollowersSummaryById(pathParams: PathParams, options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/followers/summary/" + encodeURIComponent(String(pathParams.id)) + ""
    return this.client.request({
      ...options,
      method: 'GET',
      path,
    })
  }

  async getFollowersPnlseriesById(pathParams: PathParams, options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/followers/" + encodeURIComponent(String(pathParams.id)) + "/pnl-series"
    return this.client.request({
      ...options,
      method: 'GET',
      path,
    })
  }

  async getFollowersPositionById(pathParams: PathParams, options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/followers/" + encodeURIComponent(String(pathParams.id)) + "/position"
    return this.client.request({
      ...options,
      method: 'GET',
      path,
    })
  }

  async getBots(options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/bots"
    return this.client.request({
      ...options,
      method: 'GET',
      path,
    })
  }

  async postBots(body?: JsonValue, options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/bots"
    return this.client.request({
      ...options,
      method: 'POST',
      path,
      body: body ?? options?.body,
      write: true,
    })
  }

  async getBotsById(pathParams: PathParams, options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/bots/" + encodeURIComponent(String(pathParams.id)) + ""
    return this.client.request({
      ...options,
      method: 'GET',
      path,
    })
  }

  async patchBotsById(pathParams: PathParams, body?: JsonValue, options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/bots/" + encodeURIComponent(String(pathParams.id)) + ""
    return this.client.request({
      ...options,
      method: 'PATCH',
      path,
      body: body ?? options?.body,
      write: true,
    })
  }

  async deleteBotsById(pathParams: PathParams, body?: JsonValue, options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/bots/" + encodeURIComponent(String(pathParams.id)) + ""
    return this.client.request({
      ...options,
      method: 'DELETE',
      path,
      body: body ?? options?.body,
      write: true,
    })
  }

  async postBotsSummary(body?: JsonValue, options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/bots/summary"
    return this.client.request({
      ...options,
      method: 'POST',
      path,
      body: body ?? options?.body,
    })
  }

  async getBotsPnlseriesById(pathParams: PathParams, options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/bots/" + encodeURIComponent(String(pathParams.id)) + "/pnl-series"
    return this.client.request({
      ...options,
      method: 'GET',
      path,
    })
  }

  async getBotsPositionById(pathParams: PathParams, options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/bots/" + encodeURIComponent(String(pathParams.id)) + "/position"
    return this.client.request({
      ...options,
      method: 'GET',
      path,
    })
  }

  async getEmitters(options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/emitters"
    return this.client.request({
      ...options,
      method: 'GET',
      path,
    })
  }

  async postEmitters(body?: JsonValue, options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/emitters"
    return this.client.request({
      ...options,
      method: 'POST',
      path,
      body: body ?? options?.body,
      write: true,
    })
  }

  async getEmittersById(pathParams: PathParams, options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/emitters/" + encodeURIComponent(String(pathParams.id)) + ""
    return this.client.request({
      ...options,
      method: 'GET',
      path,
    })
  }

  async patchEmittersById(pathParams: PathParams, body?: JsonValue, options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/emitters/" + encodeURIComponent(String(pathParams.id)) + ""
    return this.client.request({
      ...options,
      method: 'PATCH',
      path,
      body: body ?? options?.body,
      write: true,
    })
  }

  async deleteEmittersById(pathParams: PathParams, body?: JsonValue, options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/emitters/" + encodeURIComponent(String(pathParams.id)) + ""
    return this.client.request({
      ...options,
      method: 'DELETE',
      path,
      body: body ?? options?.body,
      write: true,
    })
  }

  async postEmittersSummary(body?: JsonValue, options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/emitters/summary"
    return this.client.request({
      ...options,
      method: 'POST',
      path,
      body: body ?? options?.body,
    })
  }

  async getEmittersSummaryById(pathParams: PathParams, options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/emitters/summary/" + encodeURIComponent(String(pathParams.id)) + ""
    return this.client.request({
      ...options,
      method: 'GET',
      path,
    })
  }

  async getEmittersCurated(options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/emitters/curated"
    return this.client.request({
      ...options,
      method: 'GET',
      path,
    })
  }

  async getEmittersPnlseriesById(pathParams: PathParams, options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/emitters/" + encodeURIComponent(String(pathParams.id)) + "/pnl-series"
    return this.client.request({
      ...options,
      method: 'GET',
      path,
    })
  }

  async getEmittersPositionById(pathParams: PathParams, options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/emitters/" + encodeURIComponent(String(pathParams.id)) + "/position"
    return this.client.request({
      ...options,
      method: 'GET',
      path,
    })
  }

  async getPortfolios(options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/portfolios"
    return this.client.request({
      ...options,
      method: 'GET',
      path,
    })
  }

  async postPortfolios(body?: JsonValue, options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/portfolios"
    return this.client.request({
      ...options,
      method: 'POST',
      path,
      body: body ?? options?.body,
      write: true,
    })
  }

  async getPortfoliosById(pathParams: PathParams, options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/portfolios/" + encodeURIComponent(String(pathParams.id)) + ""
    return this.client.request({
      ...options,
      method: 'GET',
      path,
    })
  }

  async patchPortfoliosById(pathParams: PathParams, body?: JsonValue, options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/portfolios/" + encodeURIComponent(String(pathParams.id)) + ""
    return this.client.request({
      ...options,
      method: 'PATCH',
      path,
      body: body ?? options?.body,
      write: true,
    })
  }

  async deletePortfoliosById(pathParams: PathParams, body?: JsonValue, options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/portfolios/" + encodeURIComponent(String(pathParams.id)) + ""
    return this.client.request({
      ...options,
      method: 'DELETE',
      path,
      body: body ?? options?.body,
      write: true,
    })
  }

  async postPortfoliosSummary(body?: JsonValue, options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/portfolios/summary"
    return this.client.request({
      ...options,
      method: 'POST',
      path,
      body: body ?? options?.body,
    })
  }

  async getPortfoliosPnlseriesById(pathParams: PathParams, options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/portfolios/" + encodeURIComponent(String(pathParams.id)) + "/pnl-series"
    return this.client.request({
      ...options,
      method: 'GET',
      path,
    })
  }

  async getPortfoliosPositionsById(pathParams: PathParams, options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/portfolios/" + encodeURIComponent(String(pathParams.id)) + "/positions"
    return this.client.request({
      ...options,
      method: 'GET',
      path,
    })
  }

  async getOrders(options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/orders"
    return this.client.request({
      ...options,
      method: 'GET',
      path,
    })
  }

  async getSignals(options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/signals"
    return this.client.request({
      ...options,
      method: 'GET',
      path,
    })
  }

  async getBacktestQuota(options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/backtest/quota"
    return this.client.request({
      ...options,
      method: 'GET',
      path,
    })
  }

  async getBacktests(options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/backtests"
    return this.client.request({
      ...options,
      method: 'GET',
      path,
    })
  }

  async getBacktestsSummary(options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/backtests/summary"
    return this.client.request({
      ...options,
      method: 'GET',
      path,
    })
  }

  async getBacktestByJob_id(pathParams: PathParams, options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/backtest/" + encodeURIComponent(String(pathParams.job_id)) + ""
    return this.client.request({
      ...options,
      method: 'GET',
      path,
    })
  }

  async getBacktestSignalsByJob_id(pathParams: PathParams, options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/backtest/" + encodeURIComponent(String(pathParams.job_id)) + "/signals"
    return this.client.request({
      ...options,
      method: 'GET',
      path,
    })
  }

  async getBacktestBulkSeed(options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/backtest/bulk/seed"
    return this.client.request({
      ...options,
      method: 'GET',
      path,
    })
  }

  async getBacktestBulkBatches(options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/backtest/bulk/batches"
    return this.client.request({
      ...options,
      method: 'GET',
      path,
    })
  }

  async getBacktestBulkBatchesByBatch_id(pathParams: PathParams, options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/backtest/bulk/batches/" + encodeURIComponent(String(pathParams.batch_id)) + ""
    return this.client.request({
      ...options,
      method: 'GET',
      path,
    })
  }

  async getTicker(options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/ticker"
    return this.client.request({
      ...options,
      method: 'GET',
      path,
    })
  }

  async getFundingrate(options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/funding-rate"
    return this.client.request({
      ...options,
      method: 'GET',
      path,
    })
  }

  async getMarketOrderbook(options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/market/orderbook"
    return this.client.request({
      ...options,
      method: 'GET',
      path,
    })
  }

  async getMarketTrades(options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/market/trades"
    return this.client.request({
      ...options,
      method: 'GET',
      path,
    })
  }

  async getMarkets(options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/markets"
    return this.client.request({
      ...options,
      method: 'GET',
      path,
    })
  }

  async getMarketsAssetprofile(options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/markets/asset-profile"
    return this.client.request({
      ...options,
      method: 'GET',
      path,
    })
  }

  async getExchanges(options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/exchanges"
    return this.client.request({
      ...options,
      method: 'GET',
      path,
    })
  }

  async getMarkettypes(options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/market-types"
    return this.client.request({
      ...options,
      method: 'GET',
      path,
    })
  }

  async getMarketplaceSearch(options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/marketplace/search"
    return this.client.request({
      ...options,
      method: 'GET',
      path,
    })
  }

  async getMarketplaceSellersByHandle(pathParams: PathParams, options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/marketplace/sellers/" + encodeURIComponent(String(pathParams.handle)) + ""
    return this.client.request({
      ...options,
      method: 'GET',
      path,
    })
  }

  async getDatafeedHistory(options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/datafeed/history"
    return this.client.request({
      ...options,
      method: 'GET',
      path,
    })
  }

  async postMarketsSymbolcorrelation(body?: JsonValue, options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/markets/symbol-correlation"
    return this.client.request({
      ...options,
      method: 'POST',
      path,
      body: body ?? options?.body,
    })
  }

  async postMarketsSymbolvolatility(body?: JsonValue, options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/markets/symbol-volatility"
    return this.client.request({
      ...options,
      method: 'POST',
      path,
      body: body ?? options?.body,
    })
  }

  async postMarketsSymbolfeebreakeven(body?: JsonValue, options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/markets/symbol-fee-breakeven"
    return this.client.request({
      ...options,
      method: 'POST',
      path,
      body: body ?? options?.body,
    })
  }

  async getTerminalOrders(options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/terminal/orders"
    return this.client.request({
      ...options,
      method: 'GET',
      path,
    })
  }

  async getTerminalOrdersByclientorderidByClient_order_id(pathParams: PathParams, options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/terminal/orders/by-client-order-id/" + encodeURIComponent(String(pathParams.client_order_id)) + ""
    return this.client.request({
      ...options,
      method: 'GET',
      path,
    })
  }

  async getTerminalPositions(options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/terminal/positions"
    return this.client.request({
      ...options,
      method: 'GET',
      path,
    })
  }

  async getTerminalSymbolrules(options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/terminal/symbol-rules"
    return this.client.request({
      ...options,
      method: 'GET',
      path,
    })
  }

  async getTerminalOrdercapabilities(options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/terminal/order-capabilities"
    return this.client.request({
      ...options,
      method: 'GET',
      path,
    })
  }

  async getExchangeBalances(options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/exchange/balances"
    return this.client.request({
      ...options,
      method: 'GET',
      path,
    })
  }

  async getExchangePositions(options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/exchange/positions"
    return this.client.request({
      ...options,
      method: 'GET',
      path,
    })
  }

  async getExchangeMarginsummary(options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/exchange/margin-summary"
    return this.client.request({
      ...options,
      method: 'GET',
      path,
    })
  }

  async getExchangeOrders(options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/exchange/orders"
    return this.client.request({
      ...options,
      method: 'GET',
      path,
    })
  }

  async getExchangeTrades(options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/exchange/trades"
    return this.client.request({
      ...options,
      method: 'GET',
      path,
    })
  }

  async getExchangeIncome(options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/exchange/income"
    return this.client.request({
      ...options,
      method: 'GET',
      path,
    })
  }

  async getExchangeOpenablenotional(options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/exchange/openable-notional"
    return this.client.request({
      ...options,
      method: 'GET',
      path,
    })
  }

  async postExchangeLeverage(body?: JsonValue, options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/exchange/leverage"
    return this.client.request({
      ...options,
      method: 'POST',
      path,
      body: body ?? options?.body,
      write: true,
    })
  }

  async postExchangeCancelorder(body?: JsonValue, options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/exchange/cancel-order"
    return this.client.request({
      ...options,
      method: 'POST',
      path,
      body: body ?? options?.body,
      write: true,
    })
  }

  async postExchangeCancelorders(body?: JsonValue, options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/exchange/cancel-orders"
    return this.client.request({
      ...options,
      method: 'POST',
      path,
      body: body ?? options?.body,
      write: true,
    })
  }

  async getCredentials(options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/credentials"
    return this.client.request({
      ...options,
      method: 'GET',
      path,
    })
  }

  async postCredentials(body?: JsonValue, options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/credentials"
    return this.client.request({
      ...options,
      method: 'POST',
      path,
      body: body ?? options?.body,
      write: true,
    })
  }

  async getTags(options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/tags"
    return this.client.request({
      ...options,
      method: 'GET',
      path,
    })
  }

  async postTags(body?: JsonValue, options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/tags"
    return this.client.request({
      ...options,
      method: 'POST',
      path,
      body: body ?? options?.body,
      write: true,
    })
  }

  async getMeStatisticsBytag(options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/me/statistics/by-tag"
    return this.client.request({
      ...options,
      method: 'GET',
      path,
    })
  }

  async postFollowersStartById(pathParams: PathParams, options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/followers/" + encodeURIComponent(String(pathParams.id)) + "/start"
    return this.client.request({
      ...options,
      method: 'POST',
      path,
      write: true,
    })
  }

  async postFollowersStopById(pathParams: PathParams, options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/followers/" + encodeURIComponent(String(pathParams.id)) + "/stop"
    return this.client.request({
      ...options,
      method: 'POST',
      path,
      write: true,
    })
  }

  async postBotsStartById(pathParams: PathParams, options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/bots/" + encodeURIComponent(String(pathParams.id)) + "/start"
    return this.client.request({
      ...options,
      method: 'POST',
      path,
      write: true,
    })
  }

  async postBotsStopById(pathParams: PathParams, options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/bots/" + encodeURIComponent(String(pathParams.id)) + "/stop"
    return this.client.request({
      ...options,
      method: 'POST',
      path,
      write: true,
    })
  }

  async postBotsBooksById(pathParams: PathParams, body?: JsonValue, options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/bots/" + encodeURIComponent(String(pathParams.id)) + "/books"
    return this.client.request({
      ...options,
      method: 'POST',
      path,
      body: body ?? options?.body,
      write: true,
    })
  }

  async postFollowersBooksById(pathParams: PathParams, body?: JsonValue, options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/followers/" + encodeURIComponent(String(pathParams.id)) + "/books"
    return this.client.request({
      ...options,
      method: 'POST',
      path,
      body: body ?? options?.body,
      write: true,
    })
  }

  async postEmittersStartById(pathParams: PathParams, options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/emitters/" + encodeURIComponent(String(pathParams.id)) + "/start"
    return this.client.request({
      ...options,
      method: 'POST',
      path,
      write: true,
    })
  }

  async postEmittersStopById(pathParams: PathParams, options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/emitters/" + encodeURIComponent(String(pathParams.id)) + "/stop"
    return this.client.request({
      ...options,
      method: 'POST',
      path,
      write: true,
    })
  }

  async postPortfoliosStartById(pathParams: PathParams, options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/portfolios/" + encodeURIComponent(String(pathParams.id)) + "/start"
    return this.client.request({
      ...options,
      method: 'POST',
      path,
      write: true,
    })
  }

  async postPortfoliosStopById(pathParams: PathParams, options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/portfolios/" + encodeURIComponent(String(pathParams.id)) + "/stop"
    return this.client.request({
      ...options,
      method: 'POST',
      path,
      write: true,
    })
  }

  async putFollowersTagsById(pathParams: PathParams, body?: JsonValue, options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/followers/" + encodeURIComponent(String(pathParams.id)) + "/tags"
    return this.client.request({
      ...options,
      method: 'PUT',
      path,
      body: body ?? options?.body,
      write: true,
    })
  }

  async putBotsTagsById(pathParams: PathParams, body?: JsonValue, options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/bots/" + encodeURIComponent(String(pathParams.id)) + "/tags"
    return this.client.request({
      ...options,
      method: 'PUT',
      path,
      body: body ?? options?.body,
      write: true,
    })
  }

  async putEmittersTagsById(pathParams: PathParams, body?: JsonValue, options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/emitters/" + encodeURIComponent(String(pathParams.id)) + "/tags"
    return this.client.request({
      ...options,
      method: 'PUT',
      path,
      body: body ?? options?.body,
      write: true,
    })
  }

  async putPortfoliosTagsById(pathParams: PathParams, body?: JsonValue, options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/portfolios/" + encodeURIComponent(String(pathParams.id)) + "/tags"
    return this.client.request({
      ...options,
      method: 'PUT',
      path,
      body: body ?? options?.body,
      write: true,
    })
  }

  async patchTagsById(pathParams: PathParams, body?: JsonValue, options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/tags/" + encodeURIComponent(String(pathParams.id)) + ""
    return this.client.request({
      ...options,
      method: 'PATCH',
      path,
      body: body ?? options?.body,
      write: true,
    })
  }

  async deleteTagsById(pathParams: PathParams, body?: JsonValue, options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/tags/" + encodeURIComponent(String(pathParams.id)) + ""
    return this.client.request({
      ...options,
      method: 'DELETE',
      path,
      body: body ?? options?.body,
      write: true,
    })
  }

  async putCredentialsById(pathParams: PathParams, body?: JsonValue, options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/credentials/" + encodeURIComponent(String(pathParams.id)) + ""
    return this.client.request({
      ...options,
      method: 'PUT',
      path,
      body: body ?? options?.body,
      write: true,
    })
  }

  async deleteCredentialsById(pathParams: PathParams, body?: JsonValue, options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/credentials/" + encodeURIComponent(String(pathParams.id)) + ""
    return this.client.request({
      ...options,
      method: 'DELETE',
      path,
      body: body ?? options?.body,
      write: true,
    })
  }

  async postCredentialsDefaultById(pathParams: PathParams, options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/credentials/" + encodeURIComponent(String(pathParams.id)) + "/default"
    return this.client.request({
      ...options,
      method: 'POST',
      path,
      write: true,
    })
  }

  async postBacktest(body?: JsonValue, options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/backtest"
    return this.client.request({
      ...options,
      method: 'POST',
      path,
      body: body ?? options?.body,
      write: true,
    })
  }

  async postBacktestBulk(body?: JsonValue, options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/backtest/bulk"
    return this.client.request({
      ...options,
      method: 'POST',
      path,
      body: body ?? options?.body,
      write: true,
    })
  }

  async postBacktestBulkBatchesRerunByBatch_id(pathParams: PathParams, options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/backtest/bulk/batches/" + encodeURIComponent(String(pathParams.batch_id)) + "/rerun"
    return this.client.request({
      ...options,
      method: 'POST',
      path,
      write: true,
    })
  }

  async postBacktestBulkBatchesCancelByBatch_id(pathParams: PathParams, options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/backtest/bulk/batches/" + encodeURIComponent(String(pathParams.batch_id)) + "/cancel"
    return this.client.request({
      ...options,
      method: 'POST',
      path,
      write: true,
    })
  }

  async postBacktestCancelByJob_id(pathParams: PathParams, options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/backtest/" + encodeURIComponent(String(pathParams.job_id)) + "/cancel"
    return this.client.request({
      ...options,
      method: 'POST',
      path,
      write: true,
    })
  }

  async postTerminalPlaceorder(body?: JsonValue, options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/terminal/place-order"
    return this.client.request({
      ...options,
      method: 'POST',
      path,
      body: body ?? options?.body,
      write: true,
    })
  }

  async postTerminalCancelorder(body?: JsonValue, options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/terminal/cancel-order"
    return this.client.request({
      ...options,
      method: 'POST',
      path,
      body: body ?? options?.body,
      write: true,
    })
  }

  async getAiChatQuota(options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/ai/chat/quota"
    return this.client.request({
      ...options,
      method: 'GET',
      path,
    })
  }

  async getAiChatConversations(options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/ai/chat/conversations"
    return this.client.request({
      ...options,
      method: 'GET',
      path,
    })
  }

  async postAiChatConversations(body?: JsonValue, options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/ai/chat/conversations"
    return this.client.request({
      ...options,
      method: 'POST',
      path,
      body: body ?? options?.body,
      write: true,
    })
  }

  async getAiChatConversationsById(pathParams: PathParams, options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/ai/chat/conversations/" + encodeURIComponent(String(pathParams.id)) + ""
    return this.client.request({
      ...options,
      method: 'GET',
      path,
    })
  }

  async postAiChatConversationsMessagesById(pathParams: PathParams, body?: JsonValue, options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/ai/chat/conversations/" + encodeURIComponent(String(pathParams.id)) + "/messages"
    return this.client.request({
      ...options,
      method: 'POST',
      path,
      body: body ?? options?.body,
      write: true,
    })
  }

  async postAiChatConversationsToolsConfirmByIdCall_id(pathParams: PathParams, body?: JsonValue, options?: RequestOptions): Promise<JsonValue> {
    const path = "/api/v1/ai/chat/conversations/" + encodeURIComponent(String(pathParams.id)) + "/tools/" + encodeURIComponent(String(pathParams.call_id)) + "/confirm"
    return this.client.request({
      ...options,
      method: 'POST',
      path,
      body: body ?? options?.body,
      write: true,
    })
  }

}

export const OPERATION_IDS = [
  "getMe",
  "getMeStatistics",
  "getMePositions",
  "getMePositionlegs",
  "getMeOrders",
  "getMeSignals",
  "getMeEmitters",
  "postMeEmittersSummary",
  "postAutomationsSummary",
  "getFollowers",
  "postFollowers",
  "getFollowersById",
  "patchFollowersById",
  "deleteFollowersById",
  "postFollowersSummary",
  "getFollowersSummaryById",
  "getFollowersPnlseriesById",
  "getFollowersPositionById",
  "getBots",
  "postBots",
  "getBotsById",
  "patchBotsById",
  "deleteBotsById",
  "postBotsSummary",
  "getBotsPnlseriesById",
  "getBotsPositionById",
  "getEmitters",
  "postEmitters",
  "getEmittersById",
  "patchEmittersById",
  "deleteEmittersById",
  "postEmittersSummary",
  "getEmittersSummaryById",
  "getEmittersCurated",
  "getEmittersPnlseriesById",
  "getEmittersPositionById",
  "getPortfolios",
  "postPortfolios",
  "getPortfoliosById",
  "patchPortfoliosById",
  "deletePortfoliosById",
  "postPortfoliosSummary",
  "getPortfoliosPnlseriesById",
  "getPortfoliosPositionsById",
  "getOrders",
  "getSignals",
  "getBacktestQuota",
  "getBacktests",
  "getBacktestsSummary",
  "getBacktestByJob_id",
  "getBacktestSignalsByJob_id",
  "getBacktestBulkSeed",
  "getBacktestBulkBatches",
  "getBacktestBulkBatchesByBatch_id",
  "getTicker",
  "getFundingrate",
  "getMarketOrderbook",
  "getMarketTrades",
  "getMarkets",
  "getMarketsAssetprofile",
  "getExchanges",
  "getMarkettypes",
  "getMarketplaceSearch",
  "getMarketplaceSellersByHandle",
  "getDatafeedHistory",
  "postMarketsSymbolcorrelation",
  "postMarketsSymbolvolatility",
  "postMarketsSymbolfeebreakeven",
  "getTerminalOrders",
  "getTerminalOrdersByclientorderidByClient_order_id",
  "getTerminalPositions",
  "getTerminalSymbolrules",
  "getTerminalOrdercapabilities",
  "getExchangeBalances",
  "getExchangePositions",
  "getExchangeMarginsummary",
  "getExchangeOrders",
  "getExchangeTrades",
  "getExchangeIncome",
  "getExchangeOpenablenotional",
  "postExchangeLeverage",
  "postExchangeCancelorder",
  "postExchangeCancelorders",
  "getCredentials",
  "postCredentials",
  "getTags",
  "postTags",
  "getMeStatisticsBytag",
  "postFollowersStartById",
  "postFollowersStopById",
  "postBotsStartById",
  "postBotsStopById",
  "postBotsBooksById",
  "postFollowersBooksById",
  "postEmittersStartById",
  "postEmittersStopById",
  "postPortfoliosStartById",
  "postPortfoliosStopById",
  "putFollowersTagsById",
  "putBotsTagsById",
  "putEmittersTagsById",
  "putPortfoliosTagsById",
  "patchTagsById",
  "deleteTagsById",
  "putCredentialsById",
  "deleteCredentialsById",
  "postCredentialsDefaultById",
  "postBacktest",
  "postBacktestBulk",
  "postBacktestBulkBatchesRerunByBatch_id",
  "postBacktestBulkBatchesCancelByBatch_id",
  "postBacktestCancelByJob_id",
  "postTerminalPlaceorder",
  "postTerminalCancelorder",
  "getAiChatQuota",
  "getAiChatConversations",
  "postAiChatConversations",
  "getAiChatConversationsById",
  "postAiChatConversationsMessagesById",
  "postAiChatConversationsToolsConfirmByIdCall_id",
] as const
